---
knit: "bookdown::render_book"
---

```{r, include=FALSE}
knitr::opts_chunk$set(fig.align='center') 
```


# Introduction

Snow algae are cold-adapted microalgae that bloom in melting summer snow throughout alpine and polar regions. Estimates of global coverage are lacking, but red snow algae blooms can cover vast areas of glacier summer snow in Alaska and Greenland, is present on snow overlying sea ice, and is reported from every continent. Pigments produced by the algae colors the snow red, which decreases albedo [@lutz_biogeography_2016]---by one estimate, enough to increase the rate of snow melt by 18% [@ganey_role_2017]. The impact of snow algae on global albedo, summer snow reservoirs, and nutrient cycling has hardly been studied. We still don't know the most basic facts about how snow algae blooms form: how cells colonize the white snow in the spring, what triggers snow algae to divide and produce pigment, or why one patch of snow turns red while the neighboring snow remains white. Critically, we lack basic understanding of the species composition and diversity present in snow algae blooms, which is fundamental to resolving long-standing mysteries about snow algae bloom formation.



